.PHONY: clean All

All:
	@echo "----------Building project:[ lista_jk - Debug ]----------"
	@cd "lista_jk" && "$(MAKE)" -f  "lista_jk.mk"
clean:
	@echo "----------Cleaning project:[ lista_jk - Debug ]----------"
	@cd "lista_jk" && "$(MAKE)" -f  "lista_jk.mk" clean
