.PHONY: clean All

All:
	@echo "----------Building project:[ baza - Debug ]----------"
	@cd "baza" && "$(MAKE)" -f  "baza.mk"
clean:
	@echo "----------Cleaning project:[ baza - Debug ]----------"
	@cd "baza" && "$(MAKE)" -f  "baza.mk" clean
